### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by haochange** [AdeelMufti/SNcGAN#1]
FLAGS: {'adam_beta1': 0.5, 'display_interval': 1, 'labels_names': "['Male','Smiling','Black_Hair','Blond_Hair','Mustache']", 'batch_size': 16, 'd_one_sided_label_smooth': 0.9, 'output_dir': 'output', 'd_gaussian_noise_stddev': 0.5, 'adam_beta2': 0.999, 'image_size_height': 64, 'data_name': 'celeba_conditioned', 'snapshot_interval': 2500, 'data_dir': './data/img_align_celeba', 'iterations': 100000, 'adam_alpha': 0.0002, 'labels_file': 'list_attr_celeba.txt', 'image_size_width': 52, 'd_dropout': 0.5}
Loading images...
Traceback (most recent call last):
  File "d:\PycharmProjects\SNcGAN\train.py", line 76, in <module>
    resize=(FLAGS.image_size_height, FLAGS.image_size_width)
  File "d:\PycharmProjects\SNcGAN\libs\input_helper.py", line 13, in __init__
    images = np.array([scipy.misc.imresize(scipy.misc.imread(batch_file), resize).astype(np.float) for batch_file in files]).astype(np.float32)
  File "d:\PycharmProjects\SNcGAN\libs\input_helper.py", line 13, in <listcomp>
    images = np.array([scipy.misc.imresize(scipy.misc.imread(batch_file), resize).astype(np.float) for batch_file in files]).astype(np.float32)
  File "C:\Env\Miniconda3\lib\site-packages\scipy\misc\pilutil.py", line 157, in imread
    return fromimage(im, flatten=flatten, mode=mode)
  File "C:\Env\Miniconda3\lib\site-packages\scipy\misc\pilutil.py", line 254, in fromimage
    a = array(im)
MemoryError

how to deal with it？

**Comment by AdeelMufti** [comment]
It seems that you're running out of memory (RAM) while loading the celebA images from disk. It is a very large dataset, and to speed up training, I made it load it all in memory rather than load in batches from disk every iteration. 

You have a couple of options. Reduce the physical image size in pixels even more (perhaps halving image_size_width and image_size_height in FLAGS, thus halving the memory requirement--will also train faster). Or, train with fewer data points (celebA images)--to do that, delete a portion of the celebA images from disk, or edit input_helper.py and limit the files variable to a smaller portion before they are loaded in memory (e.g. files = files[:len(files)//2]).

**Comment by haochange** [comment]
thank you.
